name: rg-connectivity-001

on:
  push:
    paths:
      - '*.tf'
  workflow_dispatch:

jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    name: 'rg-connectivity-001'

    steps:
      - uses: actions/checkout@v3

      # Azure login step
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
